---
- hosts: all
  tasks:
    - name: 'Install PHP 5'
      apt:
        name: php5
        state: latest
      become: yes
    - name: 'Install Apache2'
      apt:
        name: apache2
        state: latest
      become: yes
    - name: "Install modphp"
      apt:
        name: libapache2-mod-php5
        state: latest
      become: yes