---
- name: 'Download Wordpress installation file'
  get_url:
    url: 'https://wordpress.org/wordpress-5.0.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Unpacking Wordpress file'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes

- name: 'Create the wp-config file'
  copy: 
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Set the proper values to access the DB in the wp-config file'
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
    backup: yes
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'username_here', value: "{{ wp_db_username }}" }
    - { regex: 'password_here', value: "{{ wp_db_user_password }}" }
    - { regex: 'localhost', value: "{{ wp_db_ip }}" }
  become: yes

- name: 'Configure the Apache to serve Wordpress'
  template: 
    src: 'templates/000-default.conf'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify: 
    - restart apache