---
- name: 'Install OS dependencies'
  apt:
    name: 
      - mysql-server-5.6
      - python-mysqldb
  become: yes

- name: 'Creating the Database'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: 'root'
    # login_password: 'no password required'
    state: present

- name: 'Creating user in the Database'
  mysql_user:
    login_user: root
    name: "{{ wp_db_username }}"
    password: "{{ wp_db_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items: 
      - "{{ wp_host_ip }}"

- name: 'Configure MySql to accept remote connections'
  copy: 
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify: